make: fannkuchredux.gpp-5.c++
	/usr/bin/g++ -c $(CXXFLAGS) -std=c++11 fannkuchredux.gpp-5.c++ -o fannkuchredux.gpp-5.c++.o && /usr/bin/g++ fannkuchredux.gpp-5.c++.o -o fannkuchredux.gpp-5.gpp_run

clean:
	rm *.o *.gpp_run
#nbody.gpp-3.gpp_run: nbody.gpp-3.c++
#	/usr/bin/g++ -std=c++11 -c -pipe -O3 -fomit-frame-pointer -march=native -mfpmath=sse -msse3  nbody.gpp-3.c++ -o nbody.gpp-3.c++.o && /usr/bin/g++ nbody.gpp-3.c++.o -o nbody.gpp-3.gpp_run  
